 <a ><img src = "logo_ehtp.jpg" width = 300, align = "center"></a>
 <h1 align=center><font size = 6>Master Spécialisé  Data Engineering </font></h1>
 
 
 <h6 align=center><font size = 5 color=brown><u>BD SQL / NoSQL</u></font></h6>
 <h6 align=center><font size = 4 color=blue><u>L’objectif de ce projet est de mettre en place une base de données relationnelle (MySQL) 
    et une autre NoSQL (MongoDB) puis interroger l'ensemble de données du recensement général de la population </u></font></h6>
    
<a href="http://rgphentableaux.hcp.ma/Default1/" target="_blank">RGPH2014</a>   

<h1> Realisé par:</h1>
<mark>ZAKARIA EL HARCHAOUI<mark>

<h1>Chargement des données d’indicateurs du RGPH2014 selon les 6 thèmes</h1>

In [ ]:
import requests
import pandas as pd

import numpy as np
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
driver_exe ="chromedriver.exe"
browser = webdriver.Chrome(driver_exe)

browser.get("http://rgphentableaux.hcp.ma/Default1/")
element = browser.find_element_by_name('COMMUNELIST')
all_options = element.find_elements_by_tag_name("option")


df3 = pd.DataFrame(columns = ['A', 'B'])

In [2]:
for i in range(0,1687) :
    df3.loc[i,'Code_Commune2014']  = all_options[i].get_attribute('value')
    df3.loc[i,'Nom_Commune2014']  = all_options[i].get_attribute('text')

In [3]:
df3.drop(columns=['A', 'B'],inplace=True)

In [4]:
def fun(supprimedernierpoint):
    
    
    return supprimedernierpoint[:-1]

    

df3['Code_Commune2014'] = df3.Code_Commune2014.apply(fun)

In [5]:
import requests
   
HEADERS = {
        'Referer': 'http://rgphentableaux.hcp.ma/Default1/'}
#theme 2=demographie    
    
for i in df3.itertuples():
    url = f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={i.Code_Commune2014}.&them={2}"
   
    result = requests.get(url, headers=HEADERS).json()
    
            
#for line in result:
    
    #for k, v in line.items():
            
           # list_values = [ v for v in line.values() ]
            #columns=(list_values[0])
            #ligne=(list_values[3])

In [6]:
import requests
   
HEADERS = {
        'Referer': 'http://rgphentableaux.hcp.ma/Default1/'}
    #theme 3= handicap
    
for i in df3.itertuples():
  
    url2=f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={i.Code_Commune2014}.&them={3}"
    result2 = requests.get(url2, headers=HEADERS).json()

In [7]:
import requests
   
HEADERS = {
        'Referer': 'http://rgphentableaux.hcp.ma/Default1/'}
    #theme 4= Education et Alphabetisme
    
for i in df3.itertuples():
  
    url3=f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={i.Code_Commune2014}.&them={4}"
    result3 = requests.get(url3, headers=HEADERS).json()

In [8]:
import requests
   
HEADERS = {
        'Referer': 'http://rgphentableaux.hcp.ma/Default1/'}
    #theme 5= langues locales utilisées
    
for i in df3.itertuples():
  
    url4=f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={i.Code_Commune2014}.&them={5}"
    result4 = requests.get(url4, headers=HEADERS).json()

In [9]:
import requests
   
HEADERS = {
        'Referer': 'http://rgphentableaux.hcp.ma/Default1/'}
    #theme 6= Activité et emploi
    
for i in df3.itertuples():
  
    url5=f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={i.Code_Commune2014}.&them={6}"
    result5 = requests.get(url5, headers=HEADERS).json()

In [10]:
import requests
   
HEADERS = {
        'Referer': 'http://rgphentableaux.hcp.ma/Default1/'}
    #theme 7= Activité et emploi
    
for i in df3.itertuples():
  
    url6=f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={i.Code_Commune2014}.&them={7}"
    result6 = requests.get(url6, headers=HEADERS).json()

<h1> Commune</h1>

In [17]:
df = pd.DataFrame(columns = ['A', 'B'])
df['Code_commune']=df3['Code_Commune2014']
df['Nom_commune']=df3['Nom_Commune2014']
df.drop(columns=['A', 'B'],inplace=True)

In [18]:
df

     Code_commune       Nom_commune
0       001.01.01            Agadir
1       001.05.01          Amskroud
2       001.05.09           Drargua
3     001.05.09.3  Drargua (Centre)
4       001.05.11            Idmine
...           ...               ...
1682    591.05.02        Ain Kansra
1683    591.05.03          Laajajra
1684    591.05.05         Louadaine
1685    591.05.07      Oulad Mimoun
1686    591.05.09        Sidi Daoud

[1687 rows x 2 columns]

In [50]:
#df.to_excel(r'Commune.xlsx')

<h1>Demographie</h1>

In [19]:
#dfc.loc[dfc['Code_commune']=='001.05.09',col[0]]=val[0]
dfc = pd.DataFrame(columns = ['A', 'B'])
dfc['Code_commune']=df3['Code_Commune2014']
dfc.drop(columns=['A', 'B'],inplace=True)

In [11]:
len(result)

252

In [20]:
col=[None]*252
val=[None]*252
l=0

for j in dfc.itertuples():
    url = f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={j.Code_commune}.&them={2}"
    result = requests.get(url, headers=HEADERS).json()
    for i in range(0,252):
        if (result[i]['DATA2014']=='-' ) or (result[i]['DATA2014'] == '/'):
            
            col[i]=result[i]['INDICATEUR']
            dfc.loc[dfc['Code_commune']==j.Code_commune,col[i]]=0
            
        else:
            
            col[i]=result[i]['INDICATEUR']
            val=result[i]['DATA2014']
            dfc.loc[dfc['Code_commune']==j.Code_commune,col[i]]=val

In [21]:
dfc

,Code_commune,IEE_Population municipale,IEF_Population municipale,IEM_Population municipale,IEE_Répartition selon les grands groupes d'âges_Moins de 6 ans,IEF_Répartition selon les grands groupes d'âges_Moins de 6 ans,IEM_Répartition selon les grands groupes d'âges_Moins de 6 ans,IEE_Répartition selon les grands groupes d'âges_De 6 à 14 ans,IEF_Répartition selon les grands groupes d'âges_De 6 à 14 ans,IEM_Répartition selon les grands groupes d'âges_De 6 à 14 ans,...,IRM_État matrimonial_Veuf,IRE_Âge moyen au premier mariage,IRF_Âge moyen au premier mariage,IRM_Âge moyen au premier mariage,IRE_Fécondité_Parité moyenne à 45-49 ans,IRF_Fécondité_Parité moyenne à 45-49 ans,IRM_Fécondité_Parité moyenne à 45-49 ans,IRE_Fécondité_Indice synthétique de fécondité,IRF_Fécondité_Indice synthétique de fécondité,IRM_Fécondité_Indice synthétique de fécondité
0,001.01.01,420288,208766,211522,10.6,10.4,10.8,14.4,14.3,14.6,...,0,0,0,0,0.0,0,0.0,0.0,0,0.0
1,001.05.01,9332,4984,4348,11.5,10.7,12.3,14.5,13.4,15.7,...,0.6,29.2,27.5,31.6,0.0,3.7,0.0,0.0,2,0.0
2,001.05.09,70658,34755,35903,14.5,14.7,14.4,18,17.8,18.1,...,0.5,27.5,24.9,30.2,0.0,4.3,0.0,0.0,2.5,0.0
3,001.05.09.3,50885,24977,25908,14.8,15,14.7,18.4,18.3,18.4,...,0,0,0,0,0.0,0,0.0,0.0,0,0.0
4,001.05.11,3139,1702,1437,9.9,7.3,12.9,15.2,14.1,16.6,...,0.8,29.6,28.7,31.1,0.0,4.5,0.0,0.0,1.4,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1682,591.05.02,12291,5980,6311,12.8,12.8,12.7,18.1,17.9,18.3,...,0.4,28.2,26,30,0.0,4.6,0.0,0.0,2.3,0.0
1683,591.05.03,14476,7046,7430,13.9,13.8,13.9,19.4,19.9,18.8,...,0.7,28.6,27.1,29.9,0.0,5.4,0.0,0.0,2.8,0.0
1684,591.05.05,11767,5771,5996,13.3,12.9,13.6,19.5,19.6,19.3,...,0.5,28.3,27,29.7,0.0,5.8,0.0,0.0,1.9,0.0
1685,591.05.07,9372,4643,4729,13.8,13.4,14.3,20,20.7,19.3,...,0.7,28.8,27.5,30,0.0,5.7,0.0,0.0,2.4,0.0
1686,591.05.09,12771,6223,6548,14,14.1,13.9,18.8,18.9,18.7,...,0.6,28.8,27.5,30,0.0,6.1,0.0,0.0,2.6,0.0

In [43]:
#dfc.to_excel(r'Demographie.xlsx')

<h1>Handicap</h1>

In [22]:
dfcH = pd.DataFrame(columns = ['A', 'B'])
dfcH['Code_commune']=df3['Code_Commune2014']
dfcH.drop(columns=['A', 'B'],inplace=True)

In [23]:
len(result2)

9

In [24]:
col=[None]*9
val=[None]*9


for j in dfcH.itertuples():
    url2 = f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={j.Code_commune}.&them={3}"
    result2 = requests.get(url2, headers=HEADERS).json()
    for i in range(0,9):
        if (result2[i]['DATA2014']=='-' ) or (result2[i]['DATA2014'] == '/'):
            
            col[i]=result2[i]['INDICATEUR']
            dfcH.loc[dfcH['Code_commune']==j.Code_commune,col[i]]=0
            
        else:
            
            col[i]=result2[i]['INDICATEUR']
            val=result2[i]['DATA2014']
            dfcH.loc[dfcH['Code_commune']==j.Code_commune,col[i]]=val

In [25]:
dfcH

,Code_commune,IEE_Taux de prévalence du handicap,IEF_Taux de prévalence du handicap,IEM_Taux de prévalence du handicap,IUE_Taux de prévalence du handicap,IUF_Taux de prévalence du handicap,IUM_Taux de prévalence du handicap,IRE_Taux de prévalence du handicap,IRF_Taux de prévalence du handicap,IRM_Taux de prévalence du handicap
0,001.01.01,3.9,4.2,3.5,3.9,4.2,3.5,0,0,0
1,001.05.01,7.1,6.9,7.5,0,0,0,7.1,6.9,7.5
2,001.05.09,3.9,3.8,4,3,2.9,3,6.2,6.1,6.4
3,001.05.09.3,3,2.9,3,3,2.9,3,0,0,0
4,001.05.11,6.6,5.9,7.4,0,0,0,6.6,5.9,7.4
...,...,...,...,...,...,...,...,...,...,...
1682,591.05.02,4.8,4.7,5,0,0,0,4.8,4.7,5
1683,591.05.03,5.3,5,5.5,0,0,0,5.3,5,5.5
1684,591.05.05,4.5,4.3,4.7,0,0,0,4.5,4.3,4.7
1685,591.05.07,4.4,4.4,4.4,0,0,0,4.4,4.4,4.4
1686,591.05.09,4.6,4.1,5.1,0,0,0,4.6,4.1,5.1

In [44]:
dfcH.to_excel(r'Handicap.xlsx')

<h1>Education et Alphabetisme</h1>

In [26]:
dfcE = pd.DataFrame(columns = ['A', 'B'])
dfcE['Code_commune']=df3['Code_Commune2014']
dfcE.drop(columns=['A', 'B'],inplace=True)

In [27]:
len(result3)

108

In [28]:
col=[None]*108
val=[None]*108


for j in dfcE.itertuples():
    url3 = f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={j.Code_commune}.&them={4}"
    result3 = requests.get(url3, headers=HEADERS).json()
    for i in range(0,108):
        if (result3[i]['DATA2014']=='-' ) or (result3[i]['DATA2014'] == '/'):
            
            col[i]=result3[i]['INDICATEUR']
            dfcE.loc[dfcE['Code_commune']==j.Code_commune,col[i]]=0
            
        else:
            
            col[i]=result3[i]['INDICATEUR']
            val=result3[i]['DATA2014']
            dfcE.loc[dfcE['Code_commune']==j.Code_commune,col[i]]=val

In [29]:
dfcE

,Code_commune,IEE_Taux d'analphabétisme,IEF_Taux d'analphabétisme,IEM_Taux d'analphabétisme,IEE_Population alphabétisée de 10 ans et plus selon les langues lues et écrites_Arabe seule,IEF_Population alphabétisée de 10 ans et plus selon les langues lues et écrites_Arabe seule,IEM_Population alphabétisée de 10 ans et plus selon les langues lues et écrites_Arabe seule,IEE_Population alphabétisée de 10 ans et plus selon les langues lues et écrites_Arabe et français seules,IEF_Population alphabétisée de 10 ans et plus selon les langues lues et écrites_Arabe et français seules,IEM_Population alphabétisée de 10 ans et plus selon les langues lues et écrites_Arabe et français seules,...,IRM_Niveau d'études_Primaire,IRE_Niveau d'études_Secondaire collégial,IRF_Niveau d'études_Secondaire collégial,IRM_Niveau d'études_Secondaire collégial,IRE_Niveau d'études_Secondaire qualifiant,IRF_Niveau d'études_Secondaire qualifiant,IRM_Niveau d'études_Secondaire qualifiant,IRE_Niveau d'études_Supérieur,IRF_Niveau d'études_Supérieur,IRM_Niveau d'études_Supérieur
0,001.01.01,17.9,25.7,10.1,21,21.5,20.5,41.8,41,42.4,...,0,0,0,0,0,0,0,0,0,0
1,001.05.01,45.6,56.7,32.5,36.8,37,36.7,53.2,52,54.1,...,34.6,11,7.5,15.1,3.4,2.5,4.4,2.1,1.8,2.4
2,001.05.09,31.8,41.8,22.1,38.6,37.8,39.2,42.9,42.8,43,...,35.2,11.2,7.7,14.7,3.6,2.8,4.4,1.6,1.2,1.9
3,001.05.09.3,27.9,37.7,18.4,35.9,34.8,36.7,43.1,43,43.1,...,0,0,0,0,0,0,0,0,0,0
4,001.05.11,56.6,69,40.8,59.7,57.5,61.1,35.3,39.6,32.4,...,29.4,6.8,2.4,12,1.8,0.7,3.1,0.9,0.3,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1682,591.05.02,50.1,63.7,37.2,39.4,39.2,39.6,51.9,52.1,51.9,...,36.5,9.9,6.3,13.4,3.6,2.3,4.8,1.3,1,1.6
1683,591.05.03,55.7,70.2,42.1,51.7,55.9,49.7,44.1,41,45.6,...,36.6,7,2.6,11.2,1.7,0.7,2.6,0.5,0.2,0.9
1684,591.05.05,53.3,65.8,41.2,44,44.3,43.9,48.9,49.3,48.7,...,32.8,8.6,4.9,12.1,3.1,2.1,4.1,1.2,0.6,1.7
1685,591.05.07,58.7,73.4,44.2,49,45.7,50.6,48.4,52,46.7,...,36.9,5.2,2.4,7.9,0.9,0.2,1.6,0.3,0.1,0.6
1686,591.05.09,54.3,69,40.3,45.4,47.1,44.6,50.2,49.9,50.3,...,39.8,7,3.3,10.5,1.3,0.6,2.1,0.4,0.1,0.7

In [45]:
#dfcE.to_excel(r'Educ_Alphab.xlsx')

<H1>langues locales utilisées</H1>

In [30]:
dfcL = pd.DataFrame(columns = ['A', 'B'])
dfcL['Code_commune']=df3['Code_Commune2014']
dfcL.drop(columns=['A', 'B'],inplace=True)

In [31]:
len(result4)

45

In [32]:
col=[None]*45
val=[None]*45


for j in dfcL.itertuples():
    url4 = f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={j.Code_commune}.&them={5}"
    result4 = requests.get(url4, headers=HEADERS).json()
    for i in range(0,45):
        if (result4[i]['DATA2014']=='-' ) or (result4[i]['DATA2014'] == '/'):
            
            col[i]=result4[i]['INDICATEUR']
            dfcL.loc[dfcL['Code_commune']==j.Code_commune,col[i]]=0
            
        else:
            
            col[i]=result4[i]['INDICATEUR']
            val=result4[i]['DATA2014']
            dfcL.loc[dfcL['Code_commune']==j.Code_commune,col[i]]=val

In [33]:
dfcL

,Code_commune,IEE_Langues locales utilisées (non exclusives)_Darija,IEF_Langues locales utilisées (non exclusives)_Darija,IEM_Langues locales utilisées (non exclusives)_Darija,IEE_Langues locales utilisées (non exclusives)_Tachelhit,IEF_Langues locales utilisées (non exclusives)_Tachelhit,IEM_Langues locales utilisées (non exclusives)_Tachelhit,IEE_Langues locales utilisées (non exclusives)_Tamazight,IEF_Langues locales utilisées (non exclusives)_Tamazight,IEM_Langues locales utilisées (non exclusives)_Tamazight,...,IRM_Langues locales utilisées (non exclusives)_Tachelhit,IRE_Langues locales utilisées (non exclusives)_Tamazight,IRF_Langues locales utilisées (non exclusives)_Tamazight,IRM_Langues locales utilisées (non exclusives)_Tamazight,IRE_Langues locales utilisées (non exclusives)_Tarifit,IRF_Langues locales utilisées (non exclusives)_Tarifit,IRM_Langues locales utilisées (non exclusives)_Tarifit,IRE_Langues locales utilisées (non exclusives)_Hassania,IRF_Langues locales utilisées (non exclusives)_Hassania,IRM_Langues locales utilisées (non exclusives)_Hassania
0,001.01.01,90.5,89.5,91.4,53.7,52,55.4,1.4,1.3,1.5,...,0,0,0,0,0,0,0,0,0,0
1,001.05.01,52.1,45,60.3,98.9,98.9,98.9,0.1,0.1,0.1,...,98.9,0.1,0.1,0.1,0,0,0,0,0,0
2,001.05.09,62.7,59,66.2,79.5,79.1,79.8,1.1,1,1.1,...,90.4,0.4,0.3,0.5,0,0,0,0.9,0.9,1
3,001.05.09.3,72.9,69.3,76.3,75.2,74.6,75.8,1.3,1.3,1.3,...,0,0,0,0,0,0,0,0,0,0
4,001.05.11,27.7,15.3,42.4,99.6,99.6,99.6,0.1,0.1,0.1,...,99.6,0.1,0.1,0.1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1682,591.05.02,99.9,100,99.9,0.1,0.1,0.2,0.5,0.6,0.4,...,0.2,0.5,0.6,0.4,0.5,0.5,0.5,0,0,0
1683,591.05.03,99.9,99.9,99.9,0.1,0.1,0.1,0,0,0.1,...,0.1,0,0,0.1,0.1,0.1,0.1,0,0,0
1684,591.05.05,99.7,99.7,99.8,0.4,0.3,0.5,0.2,0.1,0.2,...,0.5,0.2,0.1,0.2,1.5,1.6,1.4,0,0,0
1685,591.05.07,99.9,99.9,99.9,0,0,0,0,0,0,...,0,0,0,0,0.1,0.1,0,0,0,0
1686,591.05.09,99.9,99.9,99.9,0,0,0,0.1,0,0.1,...,0,0.1,0,0.1,0,0,0,0,0,0

In [47]:
#dfcL.to_excel(r'Langue_Local.xlsx')

<h1>Activité et Emploie </h1>

In [34]:
dfcA = pd.DataFrame(columns = ['A', 'B'])
dfcA['Code_commune']=df3['Code_Commune2014']
dfcA.drop(columns=['A', 'B'],inplace=True)

In [35]:
len(result5)

108

In [36]:
col=[None]*108
val=[None]*108


for j in dfcA.itertuples():
    url5 = f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={j.Code_commune}.&them={6}"
    result5 = requests.get(url5, headers=HEADERS).json()
    for i in range(0,108):
        if (result5[i]['DATA2014']=='-' ) or (result5[i]['DATA2014'] == '/'):
            
            col[i]=result5[i]['INDICATEUR']
            dfcA.loc[dfcA['Code_commune']==j.Code_commune,col[i]]=0
            
        else:
            
            col[i]=result5[i]['INDICATEUR']
            val=result5[i]['DATA2014']
            dfcA.loc[dfcA['Code_commune']==j.Code_commune,col[i]]=val

In [37]:
dfcA

,Code_commune,IEE_Population selon l'activité_Population Active,IEF_Population selon l'activité_Population Active,IEM_Population selon l'activité_Population Active,IEE_Population selon l'activité_Population Inactive,IEF_Population selon l'activité_Population Inactive,IEM_Population selon l'activité_Population Inactive,IEE_Taux net d'activité,IEF_Taux net d'activité,IEM_Taux net d'activité,...,IRM_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Aide familiale,IRE_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Apprenti,IRF_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Apprenti,IRM_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Apprenti,IRE_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Associé ou partenaire,IRF_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Associé ou partenaire,IRM_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Associé ou partenaire,IRE_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Autre,IRF_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Autre,IRM_Situation dans la profession des actifs occupés et des chômeurs ayant déjà travaillé_Autre
0,001.01.01,160216,44025,116191,260072,164741,95331,50.8,28,73.5,...,0,0,0,0,0,0,0,0,0,0
1,001.05.01,2595,327,2268,6737,4657,2080,37.4,8.5,72.3,...,0.8,0.9,1.1,0.8,3.7,27.4,0.9,0.1,0.4,0
2,001.05.09,21520,2563,18957,49138,32192,16946,45,10.9,78,...,1.9,1.4,0.9,1.5,1.9,8.3,1.3,0.1,0.2,0.1
3,001.05.09.3,15696,2045,13651,35189,22932,12257,46,12.2,78.5,...,0,0,0,0,0,0,0,0,0,0
4,001.05.11,836,164,672,2303,1538,765,35.3,12,66,...,3.5,1.2,0,1.5,0.5,0.6,0.5,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1682,591.05.02,3952,175,3777,8339,5805,2534,46.2,4.2,86.1,...,18.8,0.1,0,0.1,0.8,0,0.8,0.6,0,0.7
1683,591.05.03,4424,114,4310,10052,6932,3120,45.3,2.3,85.4,...,36.5,0.1,0,0.1,1.9,3.8,1.9,0,0,0
1684,591.05.05,3882,505,3377,7885,5266,2619,47.8,12,82.5,...,31.3,1.6,1.3,1.7,1,0.2,1.1,0.2,0,0.3
1685,591.05.07,2902,152,2750,6470,4491,1979,46.6,4.9,87.2,...,32.7,0.2,0,0.2,0.9,1.5,0.9,0.3,0,0.4
1686,591.05.09,4132,351,3781,8639,5872,2767,47.9,8.3,85.3,...,33.3,0.1,0,0.1,2.6,2.8,2.6,2.1,1.9,2.1

In [48]:
#dfcA.to_excel(r'Activite_Emploi.xlsx')

<h1> Condition d'habitat </h1>

In [39]:
dfcC = pd.DataFrame(columns = ['A', 'B'])
dfcC['Code_commune']=df3['Code_Commune2014']
dfcC.drop(columns=['A', 'B'],inplace=True)

In [40]:
len(result6)

123

In [41]:
col=[None]*123
val=[None]*123


for j in dfcC.itertuples():
    url6 = f"http://rgphentableaux.hcp.ma/Default1/getDATA/?type=Commune&CGEO={j.Code_commune}.&them={7}"
    result6 = requests.get(url6, headers=HEADERS).json()
    for i in range(0,123):
        if (result6[i]['DATA2014']=='-' ) or (result6[i]['DATA2014'] == '/'):
            
            col[i]=result6[i]['INDICATEUR']
            dfcC.loc[dfcC['Code_commune']==j.Code_commune,col[i]]=0
            
        else:
            
            col[i]=result6[i]['INDICATEUR']
            val=result6[i]['DATA2014']
            dfcC.loc[dfcC['Code_commune']==j.Code_commune,col[i]]=val

In [42]:
dfcC

,Code_commune,LE_Population et ménages_Nombre de ménages,LE_Population et ménages_Taille moyenne du ménage,LE_Type de logement_Villa ou étage de villa,LE_Type de logement_Appartement dans un immeuble,LE_Type de logement_Maison marocaine Moderne,LE_Type de logement_Habitat sommaire,LE_Type de logement_Logement de type rural,LE_Type de logement_Autre,LE_Taux d'occupation du logement,...,LR_Energie utilisée pour la cuisson_Déchets des animaux,LR_Equipements ménagers_Télévision,LR_Equipements ménagers_Radio,LR_Equipements ménagers_Téléphone portable,LR_Equipements ménagers_Téléphone fixe,LR_Equipements ménagers_Internet,LR_Equipements ménagers_Ordinateur,LR_Equipements ménagers_Parabole,LR_Equipements ménagers_Réfrigérateur,LR_Distance moyenne à la route goudronnée
0,001.01.01,105057,4,5.1,20,72.3,1.4,0.1,1.1,1.2,...,0,0,0,0,0,0,0,0,0,0
1,001.05.01,2031,4.6,0.1,0.1,68.7,0.1,30.6,0.3,1.2,...,1,92.5,69.9,93.2,1.1,4.8,9.1,86.9,85,1.1
2,001.05.09,15486,4.6,1.6,2.6,86,1.1,6.7,2.1,1.5,...,0.2,86.9,68.5,94.4,1.9,6.3,10.6,76.5,77,0.3
3,001.05.09.3,11136,4.6,1.6,3.3,91.7,0.6,0.1,2.7,1.5,...,0,0,0,0,0,0,0,0,0,0
4,001.05.11,710,4.4,0.4,0,29.9,0,69.2,0.6,1.1,...,0.1,88,50.8,92.7,0.4,0.7,2,85.5,84.7,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1682,591.05.02,2232,5.5,1.2,4.2,29.7,0.3,63.5,1.2,1.7,...,18.4,91.3,33.8,93.1,0.5,2.2,3.1,81.5,84.2,1.9
1683,591.05.03,2302,6.3,0,0.4,6.1,0.1,92.6,0.7,1.8,...,24.2,71.9,35.5,81.9,0.4,1,0.6,35.8,51.7,2.4
1684,591.05.05,2035,5.8,0.8,0.1,19.5,0.6,78.1,0.8,1.6,...,16.9,86.3,34.4,90.8,1,2.7,3.8,77.1,74.8,2.6
1685,591.05.07,1659,5.6,0.1,0,3.3,0,96.1,0.5,1.6,...,4.3,81.1,49.1,85.7,0.9,1.1,1.2,69.8,60.2,1.9
1686,591.05.09,2092,6.1,0.4,0.4,1.8,0.2,96.7,0.5,1.8,...,22.8,81.7,33.1,82.3,0.5,0.9,1,56.1,59.3,1.4

In [49]:
#dfcC.to_excel(r'Cond_Habitat.xlsx')

<h1>Province</h1>

In [51]:
import requests
import pandas as pd

import numpy as np
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
driver_exe ="chromedriver.exe"
browser = webdriver.Chrome(driver_exe)

browser.get("http://rgphentableaux.hcp.ma/Default1/")
element = browser.find_element_by_name('PROVINCESLIST')
all_options = element.find_elements_by_tag_name("option")

In [53]:
df2 = pd.DataFrame(columns = ['A', 'B'])

In [55]:
for i in range(0,76) :
    df2.loc[i,'Code_province']  = all_options[i].get_attribute('value')
    df2.loc[i,'Nom_province']  = all_options[i].get_attribute('text')

In [58]:
df2.drop(columns=['A', 'B'],inplace=True)

In [59]:
df2

   Code_province    Nom_province
0     066               Aousserd
1     391          Oued Ed-Dahab
2     121               Boujdour
3     321               Laâyoune
4     537                Tarfaya
..           ...             ...
71    331                Larache
72    405               Ouezzane
73    511         Tanger-Assilah
74    571                Tétouan
75    573           M'Diq-Fnideq

[76 rows x 2 columns]

In [60]:
df2.to_excel(r'Province.xlsx')

<h1>Region</h1>

In [62]:
import requests
import pandas as pd

import numpy as np
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
driver_exe ="chromedriver.exe"
browser = webdriver.Chrome(driver_exe)

browser.get("http://rgphentableaux.hcp.ma/Default1/")
element = browser.find_element_by_name('REGIONSLIST')
all_options = element.find_elements_by_tag_name("option")

In [69]:


for i in range(0,12) :
    df1.loc[i,'Code_region']  = all_options[i].get_attribute('value')
    df1.loc[i,'Nom_Region']  = all_options[i].get_attribute('text')

In [71]:
df1.to_excel(r'Region.xlsx')

In [72]:
df1

   Code_region                 Nom_Region
0   01          Tanger-Tetouan-Al Hoceima
1   02                           Oriental
2   03                         Fès-Meknès
3   04                 Rabat-Salé-Kénitra
4   05               Béni Mellal-Khénifra
5   06                  Casablanca-Settat
6   07                     Marrakech-Safi
7   08                     Drâa-Tafilalet
8   09                        Souss-Massa
9   10                  Guelmim-Oued Noun
10  11            Laayoune-Sakia El Hamra
11  12              Eddakhla-Oued Eddahab